#!/usr/bin/env python3
"""Generate the rounding-parity fixture consumed by internal/money.

This exists because CLAUDE.md guardrail 5 says the Go rounding helpers are
*asserted* to match CPython and NumPy, not proven. This script produces the
evidence; internal/money/rounding_parity_test.go checks it with exact bit
equality.

Run it with the SAME interpreter the dashboard runs on, so the fixture is
pinned to the versions that produced the production numbers:

    make money-fixture

Values are emitted as hexadecimal float literals (float.hex()) rather than
decimal. Hex is an exact, unambiguous representation of the IEEE-754 bits, so
the fixture cannot be corrupted by a decimal round-trip on either side. Go's
strconv.ParseFloat accepts the same syntax.
"""

from __future__ import annotations

import json
import random
import sys
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent.parent.parent / "internal" / "money" / "testdata" / "rounding.json"

# Fixed seed: the fixture must be reproducible, and a diff on regeneration
# should mean a version change, never just a reroll.
SEED = 20260729


def candidates() -> list[float]:
    rng = random.Random(SEED)
    xs: list[float] = []

    # 1. Exact ties. k/8 is exactly representable in binary, so k/8 * 100 lands
    #    exactly on .5 for odd k — the round-half-to-even decision points where
    #    a naive round-half-away-from-zero implementation diverges.
    xs += [k / 8 for k in range(-4000, 4001)]

    # 2. Exact cent values — the overwhelmingly common real case.
    xs += [k / 100 for k in range(-5000, 5001)]

    # 3. Values that are decimal-looking but not binary-exact. These are where
    #    RoundCPython and RoundNumpy are most likely to disagree with each
    #    other, which is the whole reason both helpers exist.
    xs += [2.675, 1.005, 0.145, 8.835, 1.115, 2.5, 0.5, 1.5, 2.665, 0.615,
           1.265, 10.075, 100.045, 1.0049999999999999, 0.285, 0.575]

    # 4. Realistic money: sums of random cent amounts, which is what the
    #    reference actually feeds to round() after summing PayPal gross/fee.
    for _ in range(20000):
        n = rng.randint(1, 40)
        xs.append(sum(rng.randint(-20000, 20000) for _ in range(n)) / 100)

    # 5. Broad magnitude sweep, including sub-cent and large balances.
    for _ in range(20000):
        mag = rng.uniform(-6, 9)
        xs.append(rng.uniform(-1, 1) * (10**mag))

    # 6. Fee-like values: small negatives, since PayPal fees are negative for
    #    charges and net = gross + fee.
    for _ in range(5000):
        xs.append(-rng.uniform(0, 100))

    # 7. Precision boundaries.
    xs += [0.0, -0.0, 1e-9, -1e-9, 2**53 / 100, -(2**53) / 100,
           1e15, 1e16, 123456789.987654321]

    # Signed mirror so negative-branch behavior is covered everywhere.
    xs += [-x for x in xs]

    # Deduplicate on bit pattern, not on value, so 0.0 and -0.0 both survive.
    seen: set[str] = set()
    out: list[float] = []
    for x in xs:
        h = float(x).hex()
        if h not in seen:
            seen.add(h)
            out.append(float(x))
    return out


def main() -> int:
    xs = candidates()

    rows = []
    for x in xs:
        # CPython builtin round() on a Python float -> float.__round__.
        cp = round(x, 2)
        # numpy.round on a float64 scalar -> multiply/rint/divide.
        # np.float64 is returned; float() keeps the same bits.
        npy = float(np.round(np.float64(x), 2))
        rows.append({"x": x.hex(), "cpython": cp.hex(), "numpy": npy.hex()})

    payload = {
        "_comment": (
            "Generated by tools/money/gen_rounding_fixture.py. Values are hex "
            "float literals for exact IEEE-754 fidelity. Regenerate with "
            "`make money-fixture` only when deliberately changing the pinned "
            "version set below — a diff here means the parity baseline moved."
        ),
        "seed": SEED,
        "env": {
            "python": sys.version.split()[0],
            "numpy": np.__version__,
        },
        "count": len(rows),
        "cases": rows,
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w") as fh:
        json.dump(payload, fh, indent=1)
        fh.write("\n")

    disagree = sum(1 for r in rows if r["cpython"] != r["numpy"])
    print(f"wrote {OUT} ({len(rows)} cases)")
    print(f"  python {payload['env']['python']}  numpy {payload['env']['numpy']}")
    print(f"  cases where CPython and NumPy disagree: {disagree}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
