#!/usr/bin/env python3
"""Generate the summation-parity fixture consumed by internal/money.

The reference implementation sums in two different ways, and they are not
interchangeable:

  - `sum(tx["gross"] for tx in matched)` is Python's builtin sum: strictly
    left-to-right over Python floats.
  - `grp["revenue"].sum()` and `totals_df["Gross (EUR)"].sum()` are pandas
    reductions, which delegate to numpy's add.reduce and use PAIRWISE
    summation with multiple accumulators.

Pairwise and sequential can differ by an ULP, which after rounding can move a
cent. SSG runs 8-9 performances, which lands exactly on numpy's 8-element
threshold where it switches from a simple loop to eight accumulators, so this
is not a theoretical concern.

Rather than reimplement numpy's algorithm from its C source and hope the SIMD
paths agree, this fixture records what pandas ACTUALLY returns at the real call
site, and the Go test asserts against that.
"""

from __future__ import annotations

import json
import random
import sys
from pathlib import Path

import numpy as np
import pandas as pd

OUT = Path(__file__).resolve().parent.parent.parent / "internal" / "money" / "testdata" / "sums.json"

SEED = 20260729


def make_arrays() -> list[list[float]]:
    rng = random.Random(SEED)
    arrays: list[list[float]] = []

    # Lengths that straddle every branch in numpy's pairwise_sum: the n<8
    # simple loop, the n<=128 eight-accumulator block, and the recursive split
    # above 128.
    lengths = list(range(0, 40)) + [63, 64, 65, 127, 128, 129, 200, 255, 256, 257, 400, 1000]

    for n in lengths:
        # Money-shaped: euro amounts with cent precision.
        arrays.append([rng.randint(-50000, 50000) / 100 for _ in range(n)])
        # Adversarial: mixed magnitudes where association order matters most.
        arrays.append([rng.choice([1e8, -1e8, 1.0, 0.1, -0.1, 1e-8]) for _ in range(n)])
        # Realistic gross values, all positive.
        arrays.append([rng.uniform(5, 60) for _ in range(n)])
        # Realistic fees, all small negatives.
        arrays.append([-rng.uniform(0.3, 2.0) for _ in range(n)])

    # The exact shape of the TOTAL row: a handful of already-rounded values.
    for n in range(1, 20):
        arrays.append([round(rng.uniform(100, 5000), 2) for _ in range(n)])

    return arrays


def main() -> int:
    arrays = make_arrays()

    cases = []
    for a in arrays:
        s = pd.Series(a, dtype="float64")
        # What core/reconciliation.py actually calls.
        pandas_sum = float(s.sum())
        # Python's builtin sum, for contrast.
        builtin_sum = float(sum(a))

        cases.append({
            "values": [float(x).hex() for x in a],
            "pandas": float(pandas_sum).hex(),
            "builtin": float(builtin_sum).hex(),
        })

    differ = sum(1 for c in cases if c["pandas"] != c["builtin"])

    payload = {
        "_comment": (
            "Generated by tools/money/gen_sum_fixture.py. 'pandas' is "
            "Series.sum() (pairwise); 'builtin' is Python's sum() "
            "(sequential). Values are hex floats for exact fidelity."
        ),
        "seed": SEED,
        "env": {
            "python": sys.version.split()[0],
            "numpy": np.__version__,
            "pandas": pd.__version__,
        },
        "count": len(cases),
        "differing": differ,
        "cases": cases,
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w") as fh:
        json.dump(payload, fh, indent=1)
        fh.write("\n")

    print(f"wrote {OUT} ({len(cases)} arrays)")
    print(f"  pandas {pd.__version__}  numpy {np.__version__}")
    print(f"  arrays where pandas != builtin sum: {differ}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
