// Package store is the only package containing SQL.
//
// That is not a convention: .golangci.yml's `sql-lives-in-store` depguard rule
// denies pgx and database/sql everywhere except here and cmd/, so a query
// appearing in a handler is a build failure rather than a code-review catch.
//
// # Shape
//
// One table, `events`, holding one row per real-world resource keyed on
// (source, resource_id). There is no projection layer — the canonical frame is
// assembled at read time by internal/model.Assemble from the rows LoadResources
// returns. See CLAUDE.md, Persistence & read model.
//
// Queries are hand-written rather than generated by sqlc. Two of them are
// exactly where codegen is weakest — the ON CONFLICT ... DO UPDATE ... WHERE
// row-comparison guard, and FOR UPDATE SKIP LOCKED — and a dozen queries do not
// justify a codegen step and config file in a module that keeps its dependency
// list deliberately short. What sqlc would have given up (build-time detection
// of column drift) is covered by the integration suite, which fails on the
// first query.
package store

import (
	"context"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/jsilence82/ticketing-reconciliation-service/internal/store/migrate"
)

// Store owns the connection pool.
type Store struct {
	pool *pgxpool.Pool
}

// New opens a pool and verifies it can reach the database.
//
// It does NOT migrate: applying schema changes is an explicit act, not a side
// effect of connecting, so a rollback deploy cannot silently migrate forward.
func New(ctx context.Context, dsn string) (*Store, error) {
	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		return nil, fmt.Errorf("parse DATABASE_URL: %w", err)
	}

	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("open pool: %w", err)
	}

	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("ping: %w", err)
	}

	return &Store{pool: pool}, nil
}

// NewWithPool wraps an existing pool. Used by tests that need a pool configured
// with a per-test search_path.
func NewWithPool(pool *pgxpool.Pool) *Store { return &Store{pool: pool} }

// Close releases the pool.
func (s *Store) Close() { s.pool.Close() }

// Pool exposes the underlying pool for callers that legitimately need it, such
// as the test harness. Production code should use the methods.
func (s *Store) Pool() *pgxpool.Pool { return s.pool }

// Migrate applies any pending migrations.
//
// It takes a dedicated connection rather than a pooled one because the applier
// holds a session-scoped advisory lock, and a pooled connection could be handed
// to someone else mid-run.
func (s *Store) Migrate(ctx context.Context) ([]int, error) {
	conn, err := s.pool.Acquire(ctx)
	if err != nil {
		return nil, fmt.Errorf("acquire for migrate: %w", err)
	}
	defer conn.Release()

	return migrate.Apply(ctx, conn.Conn())
}

// inTx runs fn in a transaction, rolling back on error or panic.
func (s *Store) inTx(ctx context.Context, fn func(pgx.Tx) error) error {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	if err := fn(tx); err != nil {
		return err
	}
	return tx.Commit(ctx)
}

// NewScratch opens a Store on a freshly created, migrated, throwaway schema and
// returns a cleanup that drops it.
//
// Intended for tests, but deliberately free of the `testing` package so it does
// not link into production binaries and can be called from any package's tests
// without an import cycle.
func NewScratch(ctx context.Context, dsn, schema string) (*Store, func(), error) {
	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		return nil, nil, fmt.Errorf("parse DATABASE_URL: %w", err)
	}

	bootstrap, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, nil, fmt.Errorf("bootstrap pool: %w", err)
	}
	if _, err := bootstrap.Exec(ctx, "CREATE SCHEMA "+schema); err != nil {
		bootstrap.Close()
		return nil, nil, fmt.Errorf("create schema %s: %w", schema, err)
	}
	bootstrap.Close()

	// Set on the connection config so connections opened later, as the pool
	// grows, also land in this schema.
	cfg.ConnConfig.RuntimeParams["search_path"] = schema

	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, nil, fmt.Errorf("pool: %w", err)
	}

	s := NewWithPool(pool)
	if _, err := s.Migrate(ctx); err != nil {
		pool.Close()
		return nil, nil, fmt.Errorf("migrate: %w", err)
	}

	cleanup := func() {
		pool.Close()
		c, cancel := context.WithTimeout(context.Background(), 15*time.Second)
		defer cancel()
		drop, err := pgxpool.New(c, dsn)
		if err != nil {
			return
		}
		defer drop.Close()
		_, _ = drop.Exec(c, "DROP SCHEMA IF EXISTS "+schema+" CASCADE")
	}

	return s, cleanup, nil
}
